/**
 * Composite ML Scorer
 *
 * Blends all scoring layers into a single risk assessment:
 * 1. Rule Engine (existing) — pattern matching with fixed weights
 * 2. Embedding Similarity — fuzzy address/name matching via n-gram vectors
 * 3. Isolation Forest — unsupervised anomaly detection
 * 4. Gradient Boosted Classifier — supervised prediction (when trained)
 * 5. Graph Network Analysis — fraud ring detection
 *
 * Each layer produces a 0-100 score. The composite scorer weights
 * and blends them, adjusting weights based on which layers are active.
 */

import { scoreEmbeddingSimilarity, type EmbeddingResult } from './embeddings';
import { scoreIsolationForest, type IsolationForestResult } from './isolation-forest';
import { scoreGradientBoost, GradientBoostedClassifier, type PredictionResult } from './gradient-boost';
import { scoreGraphNetwork, type GraphResult } from './graph-analysis';
import type { Order } from '../types';

// ── Types ────────────────────────────────────────────────────

export interface LayerScore {
  name: string;
  score: number;         // 0-100
  weight: number;        // 0-1 (how much this layer contributes)
  active: boolean;       // is this layer producing meaningful results?
  details: string;       // human-readable explanation
  raw: any;              // full layer result for drill-down
}

export interface CompositeScore {
  /** Final blended risk score 0-100 */
  finalScore: number;
  /** Risk band derived from final score */
  riskBand: 'low' | 'medium' | 'high' | 'critical';
  /** Individual layer scores */
  layers: LayerScore[];
  /** Which layers are active */
  activeLayers: number;
  /** Human-readable summary of the composite assessment */
  summary: string;
  /** Evidence items generated by ML layers */
  mlEvidence: Array<{
    type: string;
    source: string;
    confidence: number;
    description: string;
    details: Record<string, any>;
  }>;
}

// ── Layer Weights ────────────────────────────────────────────

// Default weights when all layers are active
const DEFAULT_WEIGHTS = {
  ruleEngine: 0.30,
  embeddings: 0.20,
  isolationForest: 0.15,
  gradientBoost: 0.20,
  graphNetwork: 0.15,
};

// Weights when GBDT is not trained (redistribute its weight)
const NO_GBDT_WEIGHTS = {
  ruleEngine: 0.35,
  embeddings: 0.25,
  isolationForest: 0.20,
  gradientBoost: 0.00,
  graphNetwork: 0.20,
};

// ── Composite Scorer ─────────────────────────────────────────

/**
 * Score an order using all ML layers and blend results.
 *
 * @param order - The engine Order to score
 * @param pool - The comparison pool of all orders
 * @param ruleEngineScore - Score from the existing rule engine (0-100)
 * @param ruleEvidence - Evidence array from rule engine
 * @param gbdtModel - Trained GBDT model (null if not trained)
 */
export function scoreComposite(
  order: Order,
  pool: Order[],
  ruleEngineScore: number,
  ruleEvidence: any[],
  gbdtModel: GradientBoostedClassifier | null = null,
): CompositeScore {
  const layers: LayerScore[] = [];
  const mlEvidence: CompositeScore['mlEvidence'] = [];

  // 1. Rule Engine (already computed)
  layers.push({
    name: 'Rule Engine',
    score: ruleEngineScore,
    weight: 0, // set below
    active: true,
    details: `${ruleEvidence.length} evidence signals detected`,
    raw: { evidence: ruleEvidence },
  });

  // 2. Embedding Similarity
  let embeddingResult: EmbeddingResult;
  try {
    embeddingResult = scoreEmbeddingSimilarity(
      {
        id: order.id,
        address: order.address || '',
        customerName: order.customerName || '',
        normalizedAddress: order.normalizedAddress,
        normalizedName: order.normalizedName,
        zip: order.zip,
      },
      pool.map(o => ({
        id: o.id,
        address: o.address || '',
        customerName: o.customerName || '',
        normalizedAddress: o.normalizedAddress,
        normalizedName: o.normalizedName,
        zip: o.zip,
        disconnectDate: o.disconnectDate,
      })),
    );
  } catch {
    embeddingResult = { score: 0, addressMatches: [], nameMatches: [], details: [] };
  }

  layers.push({
    name: 'Embedding Similarity',
    score: embeddingResult.score,
    weight: 0,
    active: embeddingResult.score > 0,
    details: embeddingResult.details.length > 0
      ? embeddingResult.details[0]
      : 'No fuzzy matches detected',
    raw: embeddingResult,
  });

  // Add embedding evidence
  for (const match of embeddingResult.addressMatches) {
    mlEvidence.push({
      type: 'fuzzy_address_match',
      source: 'embeddings',
      confidence: match.similarity,
      description: `Address fuzzy-matches "${match.value}" (${(match.similarity * 100).toFixed(0)}% similar)${match.isDisconnected ? ' — DISCONNECTED account' : ''}`,
      details: {
        matchedAddress: match.value,
        similarity: match.similarity,
        isDisconnected: match.isDisconnected,
        orderId: match.id,
      },
    });
  }
  for (const match of embeddingResult.nameMatches) {
    mlEvidence.push({
      type: 'fuzzy_name_match',
      source: 'embeddings',
      confidence: match.similarity,
      description: `Customer name fuzzy-matches "${match.value}" (${(match.similarity * 100).toFixed(0)}% similar)`,
      details: {
        matchedName: match.value,
        similarity: match.similarity,
        orderId: match.id,
      },
    });
  }

  // 3. Isolation Forest
  let iforestResult: IsolationForestResult;
  try {
    iforestResult = scoreIsolationForest(order, pool);
  } catch {
    iforestResult = { score: 0, anomalyScore: 0.5, isAnomaly: false, featureImportance: [] };
  }

  layers.push({
    name: 'Isolation Forest',
    score: iforestResult.score,
    weight: 0,
    active: true,
    details: iforestResult.isAnomaly
      ? `Anomaly detected (raw score: ${iforestResult.anomalyScore.toFixed(3)})`
      : `Normal pattern (raw score: ${iforestResult.anomalyScore.toFixed(3)})`,
    raw: iforestResult,
  });

  if (iforestResult.isAnomaly) {
    const topFeatures = iforestResult.featureImportance
      .filter(f => f.contribution !== 'normal')
      .slice(0, 3);
    mlEvidence.push({
      type: 'statistical_anomaly',
      source: 'isolation_forest',
      confidence: Math.min(iforestResult.anomalyScore, 1),
      description: `Order is a statistical outlier${topFeatures.length > 0 ? ': ' + topFeatures.map(f => f.contribution).join('; ') : ''}`,
      details: {
        anomalyScore: iforestResult.anomalyScore,
        featureImportance: iforestResult.featureImportance,
      },
    });
  }

  // 4. Gradient Boosted Classifier
  let gbdtResult: PredictionResult;
  try {
    gbdtResult = scoreGradientBoost(order, pool, gbdtModel);
  } catch {
    gbdtResult = {
      probability: 0.5,
      score: 50,
      featureContributions: [],
      modelInfo: { trained: false, trainingSize: 0, accuracy: 0 },
    };
  }

  const gbdtActive = gbdtResult.modelInfo.trained;
  layers.push({
    name: 'Predictive Model',
    score: gbdtResult.score,
    weight: 0,
    active: gbdtActive,
    details: gbdtActive
      ? `Fraud probability: ${(gbdtResult.probability * 100).toFixed(1)}% (trained on ${gbdtResult.modelInfo.trainingSize} cases, ${(gbdtResult.modelInfo.accuracy * 100).toFixed(0)}% accuracy)`
      : 'Not yet trained — needs resolved cases',
    raw: gbdtResult,
  });

  if (gbdtActive && gbdtResult.probability > 0.6) {
    mlEvidence.push({
      type: 'ml_prediction',
      source: 'gradient_boost',
      confidence: gbdtResult.probability,
      description: `ML model predicts ${(gbdtResult.probability * 100).toFixed(0)}% fraud probability based on ${gbdtResult.featureContributions.length} features`,
      details: {
        probability: gbdtResult.probability,
        topContributions: gbdtResult.featureContributions.slice(0, 5),
        modelAccuracy: gbdtResult.modelInfo.accuracy,
      },
    });
  }

  // 5. Graph Network
  let graphResult: GraphResult;
  try {
    graphResult = scoreGraphNetwork(order, pool);
  } catch {
    graphResult = {
      score: 0,
      networks: [],
      connections: 0,
      directLinks: [],
      graphStats: { totalNodes: 0, totalEdges: 0, components: 0 },
    };
  }

  layers.push({
    name: 'Network Analysis',
    score: graphResult.score,
    weight: 0,
    active: graphResult.score > 0 || graphResult.networks.length > 0,
    details: graphResult.networks.length > 0
      ? `Part of ${graphResult.networks.length} fraud network(s) with ${graphResult.connections} connections`
      : `${graphResult.connections} connections found, no suspicious networks`,
    raw: graphResult,
  });

  for (const network of graphResult.networks) {
    mlEvidence.push({
      type: 'fraud_network',
      source: 'graph_analysis',
      confidence: network.riskScore / 100,
      description: network.description,
      details: {
        networkId: network.networkId,
        size: network.size,
        density: network.density,
        sharedSignals: network.sharedSignals,
        orders: network.orders,
      },
    });
  }

  // ── Compute Weighted Blend ───────────────────────────────

  const weights = gbdtActive ? DEFAULT_WEIGHTS : NO_GBDT_WEIGHTS;

  // Assign weights to layers
  layers[0].weight = weights.ruleEngine;
  layers[1].weight = weights.embeddings;
  layers[2].weight = weights.isolationForest;
  layers[3].weight = weights.gradientBoost;
  layers[4].weight = weights.graphNetwork;

  // Weighted average
  let weightedSum = 0;
  let totalWeight = 0;
  for (const layer of layers) {
    if (layer.weight > 0) {
      weightedSum += layer.score * layer.weight;
      totalWeight += layer.weight;
    }
  }

  const finalScore = totalWeight > 0
    ? Math.round(Math.min(100, Math.max(0, weightedSum / totalWeight)))
    : ruleEngineScore;

  // Risk band
  const riskBand = finalScore >= 80 ? 'critical'
    : finalScore >= 60 ? 'high'
    : finalScore >= 35 ? 'medium'
    : 'low';

  // Count active layers
  const activeLayers = layers.filter(l => l.active).length;

  // Summary
  const activeLayerNames = layers.filter(l => l.active && l.score > 0).map(l => l.name);
  const highestLayer = layers.reduce((a, b) => a.score > b.score ? a : b);

  let summary = `Composite risk score: ${finalScore}/100 (${riskBand}). `;
  summary += `${activeLayers} of ${layers.length} scoring layers active. `;

  if (mlEvidence.length > 0) {
    summary += `${mlEvidence.length} ML-generated evidence signal(s). `;
  }

  if (highestLayer.score > 50) {
    summary += `Highest signal from ${highestLayer.name} (${highestLayer.score}/100).`;
  }

  return {
    finalScore,
    riskBand,
    layers,
    activeLayers,
    summary,
    mlEvidence,
  };
}
